[package]
name = "corolla-tcu-dev-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
glib = "0.18.3"
gtk4 = "0.7.3"
plotters = "0.3.5"
plotters-backend = "0.3.5"
plotters-cairo = "0.5.0"
rand = "0.8.5"
serialport = "4.3.0"
